core/urls.py
from django.urls import path
from .views import news_feed, add_comment, delete_comment, pricing, payment, credit_card_payment, admin_payment, interview_view
from plays.views import performances_list

urlpatterns = [
    path('', performances_list, name='afisha'),
    path('news/', news_feed, name='news_feed'),
    path('add_comment/<int:news_id>/', add_comment, name='add_comment'),
    path('delete_comment/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('subscriptions', pricing, name='pricing'),
    path('payment/', payment, name='payment'),
    path('payment/credit-card/', credit_card_payment, name='credit_card_payment'),
    path('payment/admin-payment/', admin_payment, name='admin_payment'),
    path('interview/', interview_view, name='interview'),
]

gatob_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('theater/', include('theater.urls')),
    path('', include('user.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import login_view, logout_view, register_view, profile_view, profile_edit, user_view

# app_name = 'auth'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', profile_edit, name='edit_profile'),
    path('users/<str:slug>/', user_view, name='user-view'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='user/request_password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('auth/password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
]

subscription/models.py
from django.db import models
from django.contrib.auth.models import User


class Subscription(models.Model):
    PLAN_CHOICES = [
        ('monthly', 'Месячный план'),
        ('three_month', 'Трехмесячный план'),
        ('yearly', 'Годовой план'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    plan = models.CharField(max_length=20, choices=PLAN_CHOICES)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    visits = models.PositiveIntegerField(blank=True)
    priority_booking = models.BooleanField(default=True)
    ticket_discount = models.BooleanField(default=True)
    exclusive_events = models.BooleanField(default=True)
    gifts_and_bonuses = models.BooleanField(default=True)
    unlimited_visits = models.BooleanField(default=False)
    special_certificate = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s Subscription"

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    subscription = models.BooleanField(blank=False, default=False)
    avatar = models.ImageField(upload_to='avatars/', blank=True)
    phone_regex = RegexValidator(regex=r'^\+7-\d{3}-\d{3}-\d{2}-\d{2}$',
                                 message="Формат номера телефона должен быть +7-XXX-XXX-XX-XX")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    def __str__(self):
        return self.user.username

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(label="Имя пользователя", required=True, min_length=4, max_length=20,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label="Пароль", min_length=8, max_length=20,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control', 'type': 'password', 'placeholder': 'Пароль'}))


class RegisterForm(forms.ModelForm):
    repeat_password = forms.CharField(label="Повторите пароль", required=True, min_length=8, max_length=20,
                                      widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password',
                                                                        'placeholder': 'Повторите пароль'}))

    phone = forms.CharField(label="Номер телефона", required=True, max_length=17,
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+7-XXX-XXX-XX-XX'}))

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'password']
        labels = {
            'email': "Email",
            'username': "Имя пользователя",
            'first_name': "Имя",
            'last_name': "Фамилия",
            'password': "Пароль",
        }
        help_texts = {
            'username': "Не более 20 символов. Только буквы, цифры и символы @/./+/-/_."
        }
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш email'}),
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя пользователя'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите вашу фамилию'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш пароль'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.Meta.fields:
            self.fields[field_name].required = True

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if Profile.objects.filter(phone=phone).exists():
            raise ValidationError('Этот номер телефона уже занят.')
        return phone

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Этот адрес электронной почты уже занят.')
        return email

    def clean_repeat_password(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("repeat_password")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Пароли не совпадают")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(label="Аватар", required=False)

    class Meta:
        model = Profile
        fields = ['bio']
        labels = {
            'bio': "Биография",
        }
        widgets = {
            'bio': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите вашу биографию'}),
        }

user/views.py
from django.urls import reverse
from .models import Profile
from subscription.models import Subscription
from .forms import LoginForm, RegisterForm, ProfileForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


def login_view(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'user/login.html', {'form': form})

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                form.add_error(field='username', error='Invalid username or password')
        return render(request, 'user/login.html', {'form': form})


def register_view(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'user/register.html', {'form': form})
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile, created = Profile.objects.get_or_create(user=user)
            auth_data = authenticate(request, email=user.email, password=form.cleaned_data.get('password'))
            if auth_data is not None:
                login(request, auth_data)
            return redirect('login')
        else:
            return render(request, 'user/register.html', {'form': form})


def logout_view(request):
    auth.logout(request)
    return redirect('/')


def profile_edit(request):
    if request.user.is_authenticated:
        try:
            profile = Profile.objects.get(user=request.user)
        except Profile.DoesNotExist:
            profile = Profile.objects.create(user=request.user)

        if request.method == 'GET':
            form = ProfileForm(instance=profile)
            return render(request, 'user/settings.html', {'form': form})

        if request.method == 'POST':
            form = ProfileForm(request.POST, request.FILES, instance=profile)
            if form.is_valid():
                profile.bio = form.cleaned_data['bio']
                if 'avatar' in request.FILES:
                    profile.avatar = request.FILES['avatar']
                    print('Avatar uploaded:', profile.avatar)

                return HttpResponseRedirect(reverse('profile'))
    else:
        return redirect('login')


@login_required
def profile_view(request):
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)

    subscription = Subscription.objects.filter(user=request.user).first()

    return render(request, 'user/profile.html', {
        'profile': profile,
        'subscription': subscription
    })


def user_view(request, slug):
    viewed_user = get_object_or_404(Profile, username=slug)
    if request.user.is_authenticated and request.user == viewed_user:
        return redirect('profile')
    return profile_view(request)

user/templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block cssfiles %} {% endblock cssfiles %}

{% block content %}
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center"><b>Вход</b></h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <br/>
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button
                                        class="btn btn-lg btn-primary btn-block text-uppercase"
                                        type="submit"
                                >
                                    Войти
                                </button
                                >
                                <br/><br/>
                                <a
                                        class="btn btn-lg btn-warning btn-block text-uppercase"
                                        href="{% url 'password_reset' %}"
                                >Забыли пароль?</a
                                >
                            </div>
                            <small
                            ><p class="text-center mt-3">
                                Еще не зарегистрированы!
                                <a href="{% url 'register' %}"><b>Зарегистрируйтесь сейчас!</b></a>
                            </p></small
                            >
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

user/templates/user/logout.html
{% extends "base.html" %} {% load static %}
{% block content %} <br /><br />
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h5 class="card-title text-center">
            <b>You have been logged out!</b>
          </h5>
          <form class="form-signin">
            <div class="form-group">
              <a
                class="btn btn-lg btn-info btn-block text-uppercase"
                href="{% url 'login' %}"
                >Login Again</a
              >
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

user/templates/user/password_reset_complete.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_filters %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <b>Your new password has been set.</b>
                        </h5>
                        <form class="form-signin">
                            <div class="form-group">
                                <a
                                        class="btn btn-lg btn-info btn-block text-uppercase"
                                        href="{% url 'auth:login' %}"
                                >Sign In Here</a
                                >
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %} 

user/templates/user/password_reset_confirm.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load static %} {% load crispy_forms_filters %}
{% block cssfiles %} {% endblock cssfiles %} {% block content %}
    <br/>

    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center"><b>Reset Password</b></h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <br/>
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button
                                        class="btn btn-lg btn-primary btn-block text-uppercase"
                                        type="submit"
                                >
                                    Reset Password
                                </button
                                >
                                <br/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %} {% block jsfiles %}{% endblock jsfiles %}

user/templates/user/password_reset_done.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_filters %}
{% block content %}
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <b
                            >An email has been sent with instructions to reset your
                                password.</b
                            >
                        </h5>
                        <form class="form-signin">
                            <div class="form-group">
                                <a
                                        class="btn btn-lg btn-warning btn-block text-uppercase"
                                        href="https://mail.google.com/mail/u/0/"
                                >Open Gmail</a
                                >
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %} 

user/templates/user/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 my-4">
            <div class="card mb-4">
                <div class="card-header">
                    <h3 class="card-title">{{ profile.user.username }}</h3>
                </div>
                <div class="card-body">
                    <div class="profile-avatar mb-2 text-center">
                        {% if profile.avatar %}
                            <img src="{{ profile.avatar.url }}" alt="Avatar" class="img-fluid rounded-circle" style="max-width: 150px;">
                        {% else %}
                            <span style="display: flex; justify-content: center; align-items: center; width: 150px; height: 150px; border: 1px solid #ddd; border-radius: 50%;">No Avatar</span>
                        {% endif %}
                    </div>
                    <p class="card-text">{{ profile.bio }}</p>
                </div>
                <div class="card-footer text-muted">
                    <a href="{% url 'edit_profile' %}" class="btn btn-primary">Редактировать профиль</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 my-4">
            <div class="card mb-4">
                <div class="card-header">
                    <h3 class="card-title">Ваша подписка:</h3>
                </div>
                <div class="card-body">
                    {% if subscription %}
                        <h4 class="card-title">{{ subscription.get_plan_display }}</h4>
                        <p class="card-text">Цена: {{ subscription.price }} тг</p>
                        <p class="card-text">Количество посещений: {{ subscription.visits }}</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Приоритетное бронирование: {% if subscription.priority_booking %}Да{% else %}Нет{% endif %}</li>
                            <li class="list-group-item">Скидки на билеты: {% if subscription.ticket_discount %}Да{% else %}Нет{% endif %}</li>
                            <li class="list-group-item">Эксклюзивные мероприятия: {% if subscription.exclusive_events %}Да{% else %}Нет{% endif %}</li>
                            <li class="list-group-item">Подарки и бонусы: {% if subscription.gifts_and_bonuses %}Да{% else %}Нет{% endif %}</li>
                            <li class="list-group-item">Неограниченные посещения: {% if subscription.unlimited_visits %}Да{% else %}Нет{% endif %}</li>
                            <li class="list-group-item">Специальный сертификат: {% if subscription.special_certificate %}Да{% else %}Нет{% endif %}</li>
                        </ul>
                    {% else %}
                        <p class="card-text">У вас нет активной подписки.</p>
                        <a href="/subscription" class="btn btn-primary">Оформить подписку</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} {% load static %} {% load crispy_forms_filters %}
{% block content %}
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-9 col-lg-7 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center"><b>Регистрация</b></h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <br/>
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button
                                        class="btn btn-lg btn-primary btn-block text-uppercase"
                                        type="submit"
                                >
                                    Зарегистрироваться
                                </button
                                >
                                <br/><br/>
                            </div>
                            <small
                            ><p class="lead text-center">
                                Уже зарегистрированы?
                                <a href="{% url 'login' %}"><b>Войдите сейчас!</b></a>
                            </p></small
                            >
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        function formatPhoneNumber() {
            var phoneNumberInput = document.getElementById('id_phone');
            var phoneNumber = phoneNumberInput.value.replace(/\D/g, '');

            if (!phoneNumber.startsWith('7')) {
                phoneNumber = '7' + phoneNumber;
            }

            phoneNumber = phoneNumber.slice(0, 11);

            var formattedPhoneNumber = '+7';
            for (var i = 1; i < phoneNumber.length; i++) {
                if (i == 1 || i == 4 || i == 7 || i == 9) {
                    formattedPhoneNumber += '-';
                }
                formattedPhoneNumber += phoneNumber.charAt(i);
            }

            phoneNumberInput.value = formattedPhoneNumber;
        }

        $('#id_phone').on('input', formatPhoneNumber);
    </script>

{% endblock content %}

user/templates/user/request_password_reset.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}
{% block content %}
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center"><b>Reset Password</b></h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <br/>
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button
                                        class="btn btn-lg btn-primary btn-block text-uppercase"
                                        type="submit"
                                >
                                    Request Password Reset
                                </button
                                >
                                <br/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

user/templates/user/settings.html
{% extends 'base.html' %}

{% block head %}
    <title>Settings page</title>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                {% include 'header.html' %}
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12 my-4">
                <div class="col-12">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="field-wrapper">
                            {% if profile.avatar %}
                                <p>Avatar URL: {{ profile.avatar.url }}</p>
                                <label for="id_avatar" class="image-wrapper" id="image-wrapper">
                                    <img src="{{ profile.avatar.url }}" id="image-content"/>
                                </label>
                            {% else %}
                                <label for="id_avatar" class="image-wrapper" id="image-wrapper">
                                    <span style="display: flex; justify-content: center; align-items: center; width: 100%; height: 100%; text-align: center;">Change Avatar</span>
                                </label>
                            {% endif %}

                            <input id="id_avatar" type="file" name="avatar" accept="image/*" class="image_input"/>
                            <div class="text-danger">
                                {{ form.avatar.errors }}
                            </div>
                        </div>
                        <div class="field-wrapper">
                            {{ form.bio.label_tag }} {{ form.bio }}
                            <div class="text-danger">
                                {{ form.bio.errors }}
                            </div>
                        </div>
                        <button class="btn btn-primary d-block col-12 mt-2" type="submit">Save</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <script>
        const imageWrapper = document.getElementById("image-wrapper");
        const imageInput = document.getElementById("id_avatar");

        if (imageInput) {
            imageWrapper.onclick = () => {
                imageInput.click();
            };

            imageInput.onchange = evt => {
                const [file] = imageInput.files;
                if (file) {
                    const newURL = URL.createObjectURL(file);
                    const imageElement = document.getElementById('image-content');
                    if (imageElement) {
                        imageElement.src = newURL;
                    } else {
                        const newImageElement = document.createElement('img');
                        newImageElement.src = newURL;
                        newImageElement.id = 'image-content';
                        imageWrapper.innerHTML = '';
                        imageWrapper.appendChild(newImageElement);
                    }
                }
            }
        }
    </script>
{% endblock %}